name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install packages
        run: make install

      - name: test
        run: make test

      - name: format
        run: make format

      - name: lint
        run: make lint

      # - name: Generate Graph and Markdown
      #   run: python main.py
  
      # - name: Commit and Push Changes
      #   run: |
      #     git config --global user.email "alex.ackerman.j@gmail.com"
      #     git config --global user.name "ackerman-alex"
      #     git add .
      #     git commit -m "Generate graph and markdown"
      #     git push origin main